export const reducerCases = {
  SET_USER: "SET_USER",
  SET_CART_DATA: "SET_CART_DATA",
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  EMPTY_CART: "EMPTY_CART",
  UPDATE_PROD_QTY: "UPDATE_PROD_QTY",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
};
